config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    root to:"homes#top"
    get "/items" => "items#index"
    get "/items/:id" => "items#show"
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items

    get "orders/complete" => "orders#complete"
    resources :orders
    post "orders/confirm" => "orders#confirm"

    resources :destinations
    get "/about" => "homes#about"
    get "customers/my_page" => "customers#show"
    get "customers/infomation/edit" => "customers#edit"
    patch "customers/infomasion" => "customers#update"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
  end


  namespace :admin do
    root to:"homes#top"
    resources :items
    resources :genres
    resources :customers
    resources :orders
    resources :order_details

  end
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}


  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to:customer,optional: true
  belongs_to:item,optional: true

  def sub_total
    item.with_tax_price*amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:orders,dependent: :destroy
  has_many:cart_items,dependent: :destroy
  has_many:destination,dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to:customer

  def destination_display
    '〒' + postal_code + '' + address + '' + name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many:items,dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  validates :is_active,inclusion:{in:[true,false]}
  has_many:order_details,dependent: :destroy
  has_many:cart_items,dependent: :destroy
  belongs_to:genres,optional: true


  def with_tax_price
    (price * 1.1).floor
  end

  def get_image
  unless image.attached?
      file_path = Rails.root.join('app/assets/images/sweets_tarte_strawberry.png')
      image.attach(io: File.open(file_path), filename: 'sweets_tarte_strawberry.png', content_type: 'image/png')
  end
    image

  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method:{credit_card:0,transfer:1}
  enum order_status:{入金待ち:0,入金確認:1,製作中:2,発送準備中:3,発送済み:4}
  belongs_to:customer
  has_many:order_details,dependent: :destroy

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to:order
  belongs_to:item
  enum production_status:{製作不可:0,製作待ち:1,製作中:2,製作完了:3}
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
  if@customer.update(customer_params)
    redirect_to admin_customer_path
  else
    render:edit
  end
  end

  private

  def
    customer_params
    params.require(:customer).permit(:first_name,:last_name,:first_name_kana,:last_name_kana,:postal_code,:address,:telephone_number,:email,:is_deleted)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genre = Genre.new
    @genres = Genre.page(params[:page])
  end

  def create
    @genre = Genre.new(genre_params)
  if @genre.save
    redirect_to admin_genres_path
  else
    @genres = Genre.all
    render :index
  end

  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
      @genre = Genre.find(params[:id])
  if@genre.update(genre_params)
    redirect_to admin_genres_path
  else
    render :edit
  end
  end

  def destroy
    @genre.destroy
    redirect_to admin_genres_path
  end

  private

  def set_genre
    @genre = genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
    @genre = Genre.find(@item.genre_id)

  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
  if@item.update(item_params)
    redirect_to admin_items_path(@item)
  else
    render :edit
  end
  end


  private

  def item_params
    params.require(:item).permit(:name,:image,:introduction,:price,:is_active,:genre_id)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @orders = Order.page(params[:page])
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
      @order = Order.find(params[:id])
      @order.update(order_params)
      @order_details = @order.order_details

  if @order.order_status == "入金確認"
    @order_details.each do |order_detail|
      order_detail.production_status = "製作待ち"
      order_detail.save
    end
  end
    redirect_to admin_order_path
  end
  private

  def order_params
    params.require(:order).permit(:order_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if customer_signed_in?
      public_root_path
    else
      admin_root_path
    end
  end

  def after_sign_out_path_for(resource)

  if  resource == :admin
     admin_session_path
  else public_root_path
  end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
  end



end

app/helpers/admin/cutomers_helper.rb
module Admin::CutomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="col-md-4 text-center">
      <p class="bg-light"><%= @customer.first_name %>
   <%= @customer.last_name %>
  さんの会員情報編集</p>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-10 offset-md-4">
      <%= form_with model: @customer,url: admin_customer_path,method: :patch do |f| %>
      <table>
        <tr>
        <td><div class="form-group">
        <label>会員ID</label></td>
        <td colspan="2"></td>
        <td><%= @customer.id %></td>
      </div>
        </tr>
      <div class="form-group">
        <tr>
        <td><label>氏名</label></td>
        <td colspan="2"></td>
        <td><%= f.text_field:first_name,autofocus:true %>
        <%= f.text_field:last_name,autofocus:true %></td>
        </tr>
      </div>
      <div class="form-group">
        <tr>
        <td><label>カナ</label></td>
        <td colspan="2"></td>
        <td><%= f.text_field:first_name_kana,autofocus:true %>
        <%= f.text_field:last_name_kana,autofocus:true %></td>
        </tr>
      </div>
      <div class="form-group">
        <tr>
        <td><label>郵便番号</label></td>
        <td colspan="2"></td>
        <td><%= f.text_field:postal_code,autofocus:true %></td>
        </tr>
      </div>
      <div class="form-group">
        <tr>
        <td><label>住所</label></td>
        <td colspan="2"></td>
        <td><%= f.text_field:address,autofocus:true %></td>
        </tr>
      </div>
      <div class="form-group">
        <tr>
        <td><label>電話番号</label></td>
        <td colspan="2"></td>
        <td><%= f.text_field:telephone_number,autofocus:true %></td>
        </tr>
      </div>
      <div class="form-group">
        <tr>
        <td><label>メールアドレス</label></td>
        <td colspan="2"></td>
        <td><%= f.text_field:email,autofocus:true %></td>
        </tr>
      </div>
      <div class="form-group">
        <tr>
        <td><label>会員ステータス</label></td>
        <td colspan="2"></td>
        <td>
          <%= f.radio_button :is_deleted,false %>
          <%= f.label :is_deleted,'有効',value:false %>
          <%= f.radio_button :is_deleted,true %>
          <%= f.label :is_deleted,'退会',value:true %>
        </td>
      </div>
        </tr>
        <tr>
          <td><%= f.submit '変更を保存',class:'btn btn-sm btn-success' %>
          </td>
        </tr>

      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2 text-center">
      <h5 class="bg-light">会員一覧</h5>
    </div>
  </div>
  <div class="row">
    <div class="col-md-10">
      <table class="table">
        <thead>
          <tr class="table-light">
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer|  %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to admin_customer_path(customer.id) do %>
                <%= customer.first_name %>
                <%= customer.last_name %>
                <% end %>
            </td>
            <td><%= customer.email %></td>
            <td><% if customer.is_deleted %>
                  <strong class="text-secondary">退会</strong>
                <% else %>
                  <strong class="text-success">有効</strong>
                <% end %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>
<%= paginate @customers %>

app/views/admin/customers/show.html.erb
<div class="col-md-3">
      <h5 class="bg-light text-center"><%= @customer.first_name %>
   <%= @customer.last_name %>
    さんの会員詳細</h5>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <table class="table table-borderless">
        <thead>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </thead>
        <tbody>
          <tr>thead
             <td>会員ID</td>
             <td></td>
             <td><%= @customer.id %></td>
          </tr>
          <tr>
               <td>氏名</td>
               <td></td>
               <td><%= @customer.first_name %>
                 <%= @customer.last_name %></td>
          </tr>
          <tr>
                <td>フリガナ</td>
                <td></td>
                <td><%= @customer.first_name_kana %>
                     <%= @customer.last_name_kana %></td>
          </tr>
          <tr>
               <td>郵便番号</td>
               <td></td>
               <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
               <td>住所</td>
               <td ></td>
               <td><%= @customer.address %></td>
          </tr>
          <tr>
               <td>電話番号</td>
               <td></td>
               <td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
               <td>メールアドレス</td>
               <td></td>
               <td><%= @customer.email %></td>
          </tr>
          <tr>
               <td>会員ステータス</td>
               <td></td>
               <td><% if @customer.is_deleted %>
                  <strong class="text-secondary">退会</strong>
                <% else %>
                  <strong class="text-success">有効</strong>
                <% end %></td>
          </tr>
          <tr>
               <td></td>
               <td></td>
               <td><%= link_to '編集する',edit_admin_customer_path(@customer.id),class:'btn btn-sm btn-success' %></td>
               <td></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>