config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    root to:"homes#top"
    get "/items" => "items#index"
    get "/items/:id" => "items#show"
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items

    get "orders/complete" => "orders#complete"
    resources :orders
    post "orders/confirm" => "orders#confirm"

    resources :destinations
    get "/about" => "homes#about"
    get "customers/my_page" => "customers#show"
    get "customers/infomation/edit" => "customers#edit"
    patch "customers/infomasion" => "customers#update"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
  end


  namespace :admin do
    root to:"homes#top"
    resources :items
    resources :genres
    resources :customers
    resources :orders
    resources :order_details

  end
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}


  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to:customer,optional: true
  belongs_to:item,optional: true

  def sub_total
    item.with_tax_price*amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:orders,dependent: :destroy
  has_many:cart_items,dependent: :destroy
  has_many:destination,dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to:customer

  def destination_display
    '〒' + postal_code + '' + address + '' + name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many:items,dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  validates :is_active,inclusion:{in:[true,false]}
  has_many:order_details,dependent: :destroy
  has_many:cart_items,dependent: :destroy
  belongs_to:genres,optional: true


  def with_tax_price
    (price * 1.1).floor
  end

  def get_image
  unless image.attached?
      file_path = Rails.root.join('app/assets/images/sweets_tarte_strawberry.png')
      image.attach(io: File.open(file_path), filename: 'sweets_tarte_strawberry.png', content_type: 'image/png')
  end
    image

  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method:{credit_card:0,transfer:1}
  enum order_status:{入金待ち:0,入金確認:1,製作中:2,発送準備中:3,発送済み:4}
  belongs_to:customer
  has_many:order_details,dependent: :destroy

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to:order
  belongs_to:item
  enum production_status:{製作不可:0,製作待ち:1,製作中:2,製作完了:3}
end

app/controllers/admin/cutomers_controller.rb
class Admin::CutomersController < ApplicationController

  def index
    @customrs = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
  if@customer.update(customer_params)
    redirect_to admin_customer_path
  else
    render:edit
  end
  end

  private

  def
    customer_params
    params.require(:customer).permit(:first_name,:last_name,:first_name_kana,:last_name_kana,:postal_code,:address,:telephone_number,:email)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genre = Genre.new
    @genres = Genre.page(params[:page])
  end

  def create
    @genre = Genre.new(genre_params)
  if @genre.save
    redirect_to admin_genres_path
  else
    @genres = Genre.all
    render :index
  end

  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
      @genre = Genre.find(params[:id])
  if@genre.update(genre_params)
    redirect_to admin_genres_path
  else
    render :edit
  end
  end

  def destroy
    @genre.destroy
    redirect_to admin_genres_path
  end

  private

  def set_genre
    @genre = genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
    @genre = Genre.find(@item.genre_id)

  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
  if@item.update(item_params)
    redirect_to admin_items_path(@item)
  else
    render :edit
  end
  end


  private

  def item_params
    params.require(:item).permit(:name,:image,:introduction,:price,:is_active,:genre_id)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @orders = Order.page(params[:page])
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
      @order = Order.find(params[:id])
      @order.update(order_params)
      @order_details = @order.order_details

  if @order.order_status == "入金確認"
    @order_details.each do |order_detail|
      order_detail.production_status = "製作待ち"
      order_detail.save
    end
  end
    redirect_to admin_order_path
  end
  private

  def order_params
    params.require(:order).permit(:order_status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if customer_signed_in?
      public_root_path
    else
      admin_root_path
    end
  end

  def after_sign_out_path_for(resource)

  if  resource == :admin
     admin_session_path
  else public_root_path
  end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
  end



end

app/helpers/admin/cutomers_helper.rb
module Admin::CutomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="col-md-2">
   <p class="bg-light">ジャンル編集</p>
</div>
<%= form_with model: @genre,url: admin_genre_path(@genre),method: :patch do |f| %>
<div class="container">
  <div class="field">
        <%= f.label:ジャンル名 %>
        <%= f.text_field :name %>
        <%= f.submit '変更を保存',class: 'btn btn-sm btn-success' %>
  </div>
</div>
<% end %>

app/views/admin/genres/index.html.erb
<div class="col-md-2">
   <p class="bg-light">ジャンル一覧/追加</p>
</div>
<%= form_with model: @genre,url: admin_genres_path do |f| %>
<div class="container">
  <div class= "row">
    <div class="col-md-6">
      <div class="field">
        <%= f.label:ジャンル名 %>
        <%= f.text_field :name %>
        <%= f.submit '新規登録',class: 'btn btn-sm btn-success' %>

      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <table class="table">
        <thead>
          <tr class="table-secondary">
            <th>ジャンル</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @genres.each do |genre| %>
          <tr>
          <td><%= genre.name %></td>
          <td><%= link_to '編集する',edit_admin_genre_path(genre),class: 'btn btn-sm btn-success' %></td>
          <% end %>
          </tr>
        </tbody>
      </table>
      <% end %>

    </div>
  </div>
</div>
<%= paginate @genres %>

app/views/admin/items/edit.html.erb
<div class="col-md-2">
   <h5 class="bg-light">商品編集</h5>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-4">
      <%= form_with model: @item,url: admin_item_path(@item) do |f| %>
        <div class="form-group">
                <%= f.label:商品画像 %>
                <%= f.file_field :image,accept:"image/*" %>
        </div>
        <div class="form-group">
          <%= f.label:商品名 %>
          <%= f.text_field :name %>
        </div>
        <div class="form-group">
          <%= f.label:商品説明 %>
          <%= f.text_area :introduction,:size =>"30x10" %>
        </div>
        <div class="form-group">
          <%= f.label:ジャンル %>
        　<%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %>
        </div>
        <div class="form-group">
              <%= f.label:税抜価格 %>
              <%= f.text_field:price %>円
        </div>
        <div class="form-group">
                <%= f.label:ステータス %>
                <%= f.label :is_active,'販売中',value:true %>
                <%= f.radio_button :is_active,true %>
                <%= f.label :is_active,'販売停止中',value:false %>
                <%= f.radio_button :is_active,false %>
        </div>
            <%= f.submit '変更を保存',class:'btn btn-sm btn-success' %>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class ="container">
  <div class="row">
    <div class="col-md-2">
     <h5 class="bg-light text-center">商品一覧</5>
    </div>
    <div class="col-xs-6 text-light offset-9">
      <%= link_to new_admin_item_path do %>
      <button type="button" class="btn-light rounded-circle p-0 btn-md" style="width:2rem;height:2rem;">+</button>
      <% end %>
    </div>
  </div>
  <div class ="row">
    <div class="col-md-12">
      <table class="table">

        <thead>
          <tr class="table-secondary">
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td>
              <%= link_to admin_item_path(item.id) do %>
              <%= item.name %>
              <% end %>
            </td>
            <td><%= item.price.to_s(:delimited) %></td>
            <td><% genre = Genre.find(item.genre_id) %>
              <%= genre.name %></td>
            <td>
                <% if item.is_active %>
                  <strong class="text-success">販売中</strong>
                <% else %>
                  <strong class="text-secondary">販売停止中</strong>
                <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="offset-5">
  <%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div class="container">
    <div class="col-md-2">
   <p class="bg-light">商品新規登録</p>
</div>
  <%= form_with model: @item,url:'/admin/items',local:true do |f| %>
    <div class="row">
        <div class="col-md-8 offset-md-4">
                <div class="form-group">
                    <label>商品画像</label>
                    <%= f.file_field :image,accept:"image/*" %>
                </div>
                <div class="form-group">
                    <label>商品名</label>
                　　<%= f.text_field :name %>
                </div>

                <div class="form-group">
                    <label>商品説明</label>
                    <%= f.text_area :introduction,:size =>"30x10" %>
                </div>
                <div class="form-group">
                    <label>ジャンル</label>
                    <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %>
                </div>

                <div class="form-group">
                    <label>税抜価格</label>
                    <%= f.text_field :price %>円
                </div>
                <div class="form-group">
                    <label>販売ステータス</label>
                    <%= f.label :is_active,'販売中',value:true %>
                    <%= f.radio_button :is_active,true %>
                    <%= f.label :is_active,'販売停止中',value:false %>
                    <%= f.radio_button :is_active,false %>
                </div>
                    <%= f.submit '新規登録',class:'btn btn-sm btn-success'%>
                <% end %>

        </div>
    </div>
</div>

app/views/admin/items/show.html.erb
<div class="col-md-2">
   <h5 class="bg-light">商品詳細</h5>
</div>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <p><%= image_tag @item.get_image,size:"300x200" %></p>
      </div>
      <div class="col-md-8">
        <p>
          商品名
          <%= @item.name %>
        </p>
        <p>
          商品説明
          <%= @item.introduction %>
        </p>
        <p>
          ジャンル
          <%= @genre.name %>
        </p>
        <p>
          税込価格<br>
          （税抜価格）
          <%= @item.with_tax_price %>(<%= @item.price %>)円
        </p>
        <p>販売ステータス
        <strong class="text-success"><%= @item.is_active ? '販売中':'販売停止中' %></strong>
        </p>
        <%= link_to '編集する',edit_admin_item_path,class:'btn btn-am btn-success' %>
      </div>
    </div>
  </div>

app/views/admin/orders/show.html.erb
<div class="col-md-3 offset-2">
   <h5 class="bg-light text-center">注文履歴詳細</h5>
</div>
<div class="container">
    <div class="col-md-10">

      <table class="table table-borderless">
        <thead>
          <tr>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
          <td><strong>購入者</strong></td>
          <td><%= @order.customer.first_name %><%= @order.customer.last_name %></td>
        </tr>
        <tr>
          <td><strong>注文日</strong></td>
          <td>
            <%= @order.customer.created_at.to_s(:datetime_jp) %>
          </td>
        </tr>
        <tr>
          <td><strong>配送先</strong></td>
          <td>〒<%= @order.postal_code %>
                <%= @order.address %><br>
                <%= @order.name %></td>
        </tr>
        <tr>
          <td><strong>支払方法</strong></td>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <td><strong>注文ステータス</strong></td>
          <td>
            <%= form_with model: @order,url: admin_order_path(@order),method: :patch do |f| %>
          <%= f.select :order_status,["入金待ち","入金確認","製作中","発送準備中","発送済み"] %>
          <%= f.submit "更新",class:"btn btn-sm btn-success" %>
          <% end %>
          </td>

        </tr>
        </tbody>
      </table>
    </div>
    <div class="row">
      <div class= "col-md-8">

          <table class="table table-bordered">
            <thead>
              <tr class="table-secondary">
                <th class="col-md-4">商品</th>
                <th class="col-md-2">単価（税込）</th>
                <th>個数</th>
                <th>小計</th>
                <th>製造ステータス</th>
              </tr>
            </thead>

            <tbody>
              <tr>
                <% @order_details.each do |order_detail| %>
                <td><%= order_detail.item.name %></td>
                <td>¥<%= (order_detail.price).to_s(:delimited) %></td>
                <td><%= order_detail.amount %></td>
                <td>¥<%= (order_detail.price * order_detail.amount*1.1).floor.to_s(:delimited) %></td>
                <td>
                  <%= form_with model: order_detail,url:admin_order_detail_path(order_detail),method: :patch,local:true do |f| %>
                  <%= f.select :production_status,["製作不可","製作待ち","製作中","製作完了"] %>
                  <%= f.submit "更新",class:"btn btn-sm btn-success" %>
                  <% end %>
                </td>
              </tr>
            </tbody>
            <% end %>
          </table>
      </div>
      <div class="col-md-4">

        <table class="table table-borderless">
          <thead>
            <tr>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="col-md-2"><strong>商品合計</strong></td>
              <td class="col-md-2"><%= (@order.billing_amount - @order.postage).to_s(:delimited) %>円</td>
            </tr>
            <tr>
              <td><strong>送料</strong></td>
              <td><%= @order.postage.to_s(:delimited) %>円</td>
            </tr>
            <tr>
              <td><strong>請求金額合計</strong></td>
              <td><%= @order.billing_amount.to_s(:delimited) %>円</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
</div>