config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    root to:"homes#top"
    get "/items" => "items#index"
    get "/items/:id" => "items#show"
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items

    get "orders/complete" => "orders#complete"
    resources :orders
    post "orders/confirm" => "orders#confirm"

    resources :destinations
    get "/about" => "homes#about"
    get "customers/my_page" => "customers#show"
    get "customers/infomation/edit" => "customers#edit"
    patch "customers/infomasion" => "customers#update"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
  end


  namespace :admin do
    root to:"homes#top"
    resources :items
    resources :genres
    resources :customers
    resources :orders
    resources :order_details

  end
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}


  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to:customer,optional: true
  belongs_to:item,optional: true

  def sub_total
    item.with_tax_price*amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:orders,dependent: :destroy
  has_many:cart_items,dependent: :destroy
  has_many:destination,dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to:customer

  def destination_display
    '〒' + postal_code + '' + address + '' + name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many:items,dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  validates :is_active,inclusion:{in:[true,false]}
  has_many:order_details,dependent: :destroy
  has_many:cart_items,dependent: :destroy
  belongs_to:genres,optional: true


  def with_tax_price
    (price * 1.1).floor
  end

  def get_image
  unless image.attached?
      file_path = Rails.root.join('app/assets/images/sweets_tarte_strawberry.png')
      image.attach(io: File.open(file_path), filename: 'sweets_tarte_strawberry.png', content_type: 'image/png')
  end
    image

  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method:{credit_card:0,transfer:1}
  enum order_status:{入金待ち:0,入金確認:1,製作中:2,発送準備中:3,発送済み:4}
  belongs_to:customer
  has_many:order_details,dependent: :destroy

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to:order
  belongs_to:item
  enum production_status:{製作不可:0,製作待ち:1,製作中:2,製作完了:3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genre = Genre.new
    @genres = Genre.page(params[:page])
  end

  def create
    @genre = Genre.new(genre_params)
  if @genre.save
    redirect_to admin_genres_path
  else
    @genres = Genre.all
    render :index
  end

  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
      @genre = Genre.find(params[:id])
  if@genre.update(genre_params)
    redirect_to admin_genres_path
  else
    render :edit
  end
  end

  def destroy
    @genre.destroy
    redirect_to admin_genres_path
  end

  private

  def set_genre
    @genre = genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
    @genre = Genre.find(@item.genre_id)

  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
  if@item.update(item_params)
    redirect_to admin_items_path(@item)
  else
    render :edit
  end
  end


  private

  def item_params
    params.require(:item).permit(:name,:image,:introduction,:price,:is_active,:genre_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if customer_signed_in?
      public_root_path
    else
      admin_root_path
    end
  end

  def after_sign_out_path_for(resource)

  if  resource == :admin
     admin_session_path
  else public_root_path
  end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
  end



end

app/helpers/admin/cutomers_helper.rb
module Admin::CutomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://kit.fontawesome.com/0fcbfc5bc0.js" crossorigin="anonymous"></script>
    <title>Naganocake</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content ="width=device-width,intial-scal=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand p-3" href="/public">
            <span>naganocake</span>
          </a>

            <ul class ="navbar-nav ml-auto">

            <% if admin_signed_in? %>
            <li class ="nav-item">
            <%= link_to admin_items_path,class:"btn btn-outline-secondary text-dark" do %>
            商品一覧
            <% end %>
            </li>
            <li class ="nav-item">
              <%= link_to admin_customers_path,class:"btn btn-outline-secondary text-dark" do %>
              会員一覧
              <% end %>
            </li>
            <li class ="nav-item">
              <%= link_to admin_root_path,class:"btn btn-outline-secondary text-dark" do %>
              注文一覧
              <% end %>
            </li>
            <li class ="nav-item">
              <%= link_to admin_genres_path,class:"btn btn-outline-secondary text-dark" do %>
              ジャンル一覧
              <% end %>
            </li>
            <li class ="nav-item">
              <%= link_to destroy_admin_session_path,method: :delete,class:"nav-link btn btn-outline-secondary text-dark" do %>
              ログアウト
              <% end %>
            </li>

            <% elsif customer_signed_in? %>
            <li class="mx-auto">
              ようこそ<%= current_customer.first_name %>さん！
            </li>
            <li class ="nav-item">
            <%= link_to public_customers_my_page_path,class:"btn btn-outline-secondary text-dark" do %>
            マイページ
            <% end %>
            </li>
            <li class ="nav-item">
              <%= link_to public_items_path,class:"btn btn-outline-secondary text-dark" do %>
              商品一覧
              <% end %>
            </li>
            <li class ="nav-item">
              <%= link_to public_cart_items_path,class:"btn btn-outline-secondary text-dark" do %>
              カート
              <% end %>
            </li>
            <li class="nav-item">
               <%= link_to destroy_customer_session_path,method: :delete,class:" btn btn-outline-secondary text-dark" do %>
               ログアウト
               <% end %>
            </li>
            <% else %>

            <li class ="nav-item">
            <%= link_to public_about_path,class:"btn btn-outline-secondary text-dark" do %>
            About
            <% end %>
            </li>
            <li class ="nav-item">
            <%= link_to admin_items_path,class:"btn btn-outline-secondary text-dark" do %>
            商品一覧
            <% end %>
            </li>
            <li class ="nav-item">
            <%= link_to new_customer_registration_path,class:"btn btn-outline-secondary text-dark" do %>
            新規登録
            <% end %>
            </li>
            <li class ="nav-item">
            <%= link_to customer_session_path,class:"btn btn-outline-secondary text-dark" do %>
            ログイン
            <% end %>
            </li>

            <% end %>

        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
  <footer>
    <div class ="container mt-5">
      <div class="row">
      <div class ="mx-auto">
      <p>CopyRight Hikaru.inc</p>
      </div>
      </div>
    </div>

  </footer>
</html>